---
- name: "Fail2ban - install"
  package:
    name: fail2ban
    state: latest
  notify:
  - fail2ban_enable
  - fail2ban_start
  tags: fail2ban_install

- block:
  - name: "Fail2ban - systemd config"
    template:
      src: 00-systemd.conf.j2
      dest: /etc/fail2ban/jail.d/00-systemd.conf
    notify: fail2ban_restart
    tags: fail2ban_config_systemd

  - name: "Fail2ban - local config"
    template:
      src: local.conf.j2
      dest: /etc/fail2ban/jail.d/local.conf
    notify: fail2ban_restart
    tags: fail2ban_config_local
  - name: "Fail2ban - forse to start"
    systemd:
      name: fail2ban
      state: started
      enabled: true
      daemon-reload: true
    notify: fail2ban_restart
    tags: fail2ban_start
  tags: fail2ban_config

- name: "Fail2ban - readable /var/log/fail2ban.log"
  file:
    path: /var/log/fail2ban.log
    owner: root
    group: root
    mode: 0644
  tags: fail2ban_log

# Netdata alerting
#- block:
#  - name: "Alerts - setting Netdata alert"
#    template:
#      src: netdata_alert.conf.j2
#      dest: /etc/netdata/health.d/fail2ban.conf
#    ignore_errors: True
#    notify: netdata_restart
#  when: role_fail2ban.netdata_alert.use
#  tags: fail2ban_alert
